# Uplift configuration for semantic versioning
# https://upliftci.dev/

# Conventional commit configuration
git:
  ignoreDetached: false
  ignoreShallow: false

# Bump configuration
bumps:
  - file: cmd/az/main.go
    regex:
      - pattern: 'version = "(.*)"'
        semver: true

# Changelog configuration
changelog:
  skip: true  # We use git-cliff for changelog generation

# Git commit and tag configuration
commitMessage: |
  chore: release version $VERSION

  $CHANGES

tagMessage: |
  Release $VERSION
