# Uplift configuration for semantic versioning
# https://upliftci.dev/

# Git configuration
git:
  ignoreDetached: false
  ignoreShallow: false

# Commit message template
commitMessage: "chore: release version $VERSION"

# Changelog configuration - skip to use git-cliff instead
changelog:
  skip: true
