package sas

import (
	"encoding/xml"
	"testing"
	"time"
)

// TestUserDelegationKeyInfoBody locks the GetUserDelegationCredential request
// body byte-for-byte against azblob v1.7.0. Golden generated by marshalling a
// real service.KeyInfo with encoding/xml in a standalone module pinned to
// azblob v1.7.0 (no custom MarshalXML exists on the type, so declaration
// order in zz_models.go drives element order: Expiry, then Start, then
// DelegatedUserTid).
func TestUserDelegationKeyInfoBody(t *testing.T) {
	start := time.Date(2026, 1, 1, 0, 0, 0, 0, time.UTC)
	expiry := time.Date(2026, 1, 2, 0, 0, 0, 0, time.UTC)

	t.Run("with tid", func(t *testing.T) {
		info := UserDelegationKeyInfo(start, expiry, "11111111-2222-3333-4444-555555555555")
		b, err := xml.Marshal(info)
		if err != nil {
			t.Fatalf("xml.Marshal: %v", err)
		}
		want := `<KeyInfo><Expiry>2026-01-02T00:00:00Z</Expiry><Start>2026-01-01T00:00:00Z</Start><DelegatedUserTid>11111111-2222-3333-4444-555555555555</DelegatedUserTid></KeyInfo>`
		if string(b) != want {
			t.Errorf("body = %q, want %q", string(b), want)
		}
	})

	t.Run("without tid", func(t *testing.T) {
		info := UserDelegationKeyInfo(start, expiry, "")
		b, err := xml.Marshal(info)
		if err != nil {
			t.Fatalf("xml.Marshal: %v", err)
		}
		want := `<KeyInfo><Expiry>2026-01-02T00:00:00Z</Expiry><Start>2026-01-01T00:00:00Z</Start></KeyInfo>`
		if string(b) != want {
			t.Errorf("body = %q, want %q", string(b), want)
		}
	})
}
